### ISSUE TITLE
Make license for this resource explicit

### ISSUE THREAD

**Issue by cthoyt** [yuki-yamagata/hoip#2]
Hi @yuki-yamagata, could you add a LICENSE file in this repository to make it clear under what license its content can be reused?

**Comment by yuki-yamagata** [comment]
Hi @cthoyt , I'd like to add a LICENSE file, CC BY 4.0](https://creativecommons.org/licenses/by/4.0/.
But could you tell me how to make the file?
Thank you for supporting.

**Comment by cthoyt** [comment]
Good morning, I used GitHub's license template adder and made a PR in https://github.com/yuki-yamagata/hoip/pull/3.

**Comment by yuki-yamagata** [comment]
Thank you!
I just noticed that this is a HoIP ontology repository as an extension of TXPO.

I am also developing TXPO, which joins OBO. The project I was a part of before is finished and I am maintaining it alone, so I am not able to ask SEs about it now and I don't understand it well.
(I am an ontologist who manually annotates and creates OWL files.)
Perhaps you are asking about the TXPO license?
I would like to CC by 4.0 for that too, but I don't know how to change YAML files and so on, since I had asked my outsourced SE to do it for me.

The project was finished in my previous institute, and I am maintaining the TXPO alone, so I cannot ask Tech people about it now. 
I don't understand it well...
I am an ontologist who manually annotates and creates OWL files.
Perhaps you are asking about the TXPO license?
I would like to CC by 4.0 for that too, but I don't know how to change YAML files and so on.

**Comment by yuki-yamagata** [comment]
Sorry, @cthoyt   
I closed it by mistake.
Thank you! 
I just noticed that this is a HoIP ontology repository as an extension of TXPO.

I am also developing TXPO, which joins OBO. 
The project was finished in my previous institute, and I am maintaining the TXPO alone, so I cannot ask Tech people about it now. 
I don't understand it well...
I am an ontologist who manually annotates and creates OWL files.
Perhaps you are asking about the TXPO license?
I would like to CC by 4.0 for that too, but I don't know how to change YAML files and so on.

**Comment by cthoyt** [comment]
No, I am quite certain I would like to make the license for HoIP explicit in this repository. I am aware you work on TXPO and this issue has nothing to do with that.

In the first lines of https://github.com/yuki-yamagata/hoip/blob/master/hoip_0308.owl, it's explicit, but this is not sufficient for looking up metadata via GitHub.

```owl
...
        <dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Homeostasis imbalance process ontology (HOIP)</dc:title>
        <terms:license rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://creativecommons.org/licenses/by/4.0/</terms:license>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">We are currently focus on COVID-19 infectious process triggered by SARS-CoV2 entry.
http://purl.bioontology.org/ontology/HOIP/HOIP_0037002</rdfs:comment>
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2022/03/08</owl:versionInfo>
    </owl:Ontology>
```

**Comment by yuki-yamagata** [comment]
Oh, thank you！ May I close this issue?
